### ISSUE TITLE
Quiz Discussion Screen

### ISSUE THREAD

**Issue by CoderVishalSehgal** [UdacityAndroidDevScholarship/quiz-app#103]
**Complete By: 7th May 2018 EOD**

This is the Discussion Screen UI for contacting quiz creators and community members and asking them for any help and open discussion regarding Quiz.

1. follow the design, see *home* package for the sample. 
2. Create Contract which must contain Presenter and View interfaces. Make the Activity implement this **View** interface.
3. create a package  **...ui/discussion** and add all these files.
4. Layout wise create an `item_discussion.xml` and `activity_quiz_discussion.xml`. Use any layout you find suitable and use `recyclerview` inside it.
5. Create a recycler view adapter that supports additions of `models/Comment` items.

**UI Requirements:**

* It contains a RecyclerView.
* RecyclerView item should contain a profile picture, name, time.
* Chat bubble with description text.
* EditText and send button just like Whatsapp. 

**Sample UI link**: https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#quiz-discussion-activity

**Comment by vibhuti16** [comment]
can i claim this?

**Comment by vibhuti16** [comment]
ill start working on this

**Comment by CoderVishalSehgal** [comment]
@vibhuti16 yes, go ahead 👍

**Comment by intkhabahmed** [comment]
@CoderVishalSehgal I would ike to work on it

**Comment by CoderVishalSehgal** [comment]
Yes go ahead @intkhabahmed  :+1:

**Comment by intkhabahmed** [comment]
@CoderVishalSehgal the chat will be between only two persons or there can be multiple persons

**Comment by CoderVishalSehgal** [comment]
@intkhabahmed It will be b/w, multiple persons.

**Comment by intkhabahmed** [comment]
@CoderVishalSehgal one more thing, I saw the latest code and there are many things missing, like there are string resources that are missing, NotificationContract class was having default access modifier instead of public. who left all these things?

**Comment by intkhabahmed** [comment]
@drulabs Still the string resource in the quiz adapter is missing

**Comment by drulabs** [comment]
@intkhabahmed which resource. I can run the app. Please mention the resource name

**Comment by intkhabahmed** [comment]
@drulabs now its OK, maybe it was build problem

**Comment by vibhuti16** [comment]
do we offline storage here?

**Comment by drulabs** [comment]
@vibhuti16 no. It is all online only. However since we are using firebase we, the offline part is already taken care of.

**Comment by vibhuti16** [comment]
https://github.com/UdacityAndroidDevScholarship/quiz-app/pull/108

**Comment by aditisoni8899** [comment]
@jainakshansh sure. Go ahead.

**Comment by nishank95** [comment]
Hey @vibhuti16  insert the issue number in your PR at the first line like this "Fixes #108" instead of keeping it Fixes #[Insert_issue_number_here] so your PR will get reference to this issue.

**Comment by mdrahil** [comment]
I want to work on this. Can I implement it?

**Comment by drulabs** [comment]
@mdrahil, @jainakshansh please try to submit the PRs by today EOD.

**Comment by jainakshansh** [comment]
@drulabs, I have already submitted a PR for the UI.
I wouldn't be able to do it for the code because of time constraints since I have my semesters going on. Sorry! I'll still try if it will be possible.

**Comment by aditisoni8899** [comment]
Merged #126 @mdrahil 's PR. Closing this issue.
