### ISSUE TITLE
Quiz Details Screen UI

### ISSUE THREAD

**Issue by CoderVishalSehgal** [UdacityAndroidDevScholarship/quiz-app#104]
**Complete By: 8th May 2018 EOD**

This is the Quiz Details Screen UI which gives more information about the specific quiz.

* Textual content inside the card must be in a **ScrollView**.
* Help Button Icon is present in the drawable folder named as **ic_help**.

For requirements please refer to the sample *UI* Link: 
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#quiz-details-activity

**Comment by xsahil03x** [comment]
I would like to work on this.

**Comment by thayumaanavan** [comment]
@xsahil03x yes, please go ahead.

**Comment by derrickabreo** [comment]
I would like to work on this too. Should I create an XML layout resource file or an activity?

**Comment by drulabs** [comment]
@derrickabreo yes. Please go ahead.

**Comment by nishank95** [comment]
Can I work on this I can submit till EOD

**Comment by drulabs** [comment]
Issue deadline is extended till tomorrow EOD. @nishank95 sure, go ahead.

**Comment by aditisoni8899** [comment]
Merged @xsahil03x's PR. Closing this Issue.
