### ISSUE TITLE
Settings Activity

### ISSUE THREAD

**Issue by CoderVishalSehgal** [UdacityAndroidDevScholarship/quiz-app#105]
**Complete By: 8th May 2018 EOD**

This is the settings activity of the QuizApp and it contains some basic settings.

**Requirements:**
* It must contain three items, check out the sample UI.
* Create a **SettingsActivity.java**.
* Create a *settings_app.xml* inside the *res/xml* folder and add the **PreferenceScreen** inside that activity and the respective items as shown in mockups.
* Create a custom dialog Preference name it *SignOutDialogPreference.java* for Signout.
* Theme *entries* and *entryValues* should be **Dark and Light** and default values as *Dark*.

**Sample UI**:
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#settings-activity

**Comment by YuganshT79** [comment]
I would like to work on this, Do we have to also create the `SettingsActivity.java` or just the XML file and `CustomDialog` ?

**Comment by CoderVishalSehgal** [comment]
Yes, go ahead and also have to make **SettingsActivity.java** 👍

**Comment by sud8443** [comment]
@CoderVishalSehgal can I work on this ?

**Comment by drulabs** [comment]
@sud8443 please go ahead.

**Comment by aditisoni8899** [comment]
@jainakshansh sure. Go Ahead.

**Comment by sayaMahi** [comment]
I shall work on this.

**Comment by thayumaanavan** [comment]
@sayaMahi Yes.. Please go ahead.

**Comment by imashwani** [comment]
hey i am working on this and make a pull request in few hours

**Comment by rdias002** [comment]
i am going to start my first ever group project contribution. i'm planning to start here, shall i?

**Comment by drulabs** [comment]
The issues deadline is extended til tomorrow EOD.

**Comment by bhatnagar-gaurav** [comment]
I will also like to work on this specific issue.

**Comment by Suparna-here** [comment]
I will start working on this issue.

**Comment by drulabs** [comment]
@Suparna-here sure go ahead. Please ensure you familiarise yourself the [contribution guidelines](https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/Contribution-Guidelines) before you start working.
Also today EOD is the last date, please create a PR by today EOD.

**Comment by Suparna-here** [comment]
I have read the contribution guideline and just created fork from development branch(chosen it from drop down list) in gihub. In my account, it is showing 
Forked from UdacityAndroidDevScholarship/quiz-app
When I clicked the above link it just redirect me to master branch of quiz-app. Is the fork created correctly  , can you please confirm? As this is my first contribution to collaborative project. As my son fall sick I was not active in April. Please help. It will help me to contribute in project after a carrier break.

**Comment by akshaychopra96** [comment]
I would also like to work on this issue. May I? I will submit the PR today only.

**Comment by drulabs** [comment]
@akshaychopra96 sure, you can submit PR by today EOD.

**Comment by Suparna-here** [comment]
Does "Get Notifications" and "Theme" option have to be functional or just show dummy state?

**Comment by Suparna-here** [comment]
in activity_main.xml settings and about are textViews, not part of menu. So where from I should launch SettingsActivity?

**Comment by Suparna-here** [comment]
I need to modify Navigation Drawer menu and Presenter code to add Settings item. Both are knew to me as not covered under course. Please give some more time.

**Comment by Suparna-here** [comment]
Can I submit pull request in repository for issue #105, whose EOD was 8th may. Kindly confirm. I just completed it. I have not yet contributed in collaborative project.

**Comment by Suparna-here** [comment]
I am in process to resolve conflicts. will submit PR with in 3 hours.

**Comment by vansh1sh** [comment]
Resolved. Closing this issue. Most appropriate PR will be merged soon.

**Comment by vansh1sh** [comment]
@Suparna-here Please create the PR as soon as possible (Please raise it within an hour, if possible).
