### ISSUE TITLE
Application Icon Update

### ISSUE THREAD

**Issue by shubhamv1436** [UdacityAndroidDevScholarship/quiz-app#11]
### Environment
  * Android studio version : 3.0.1
  * Operating system : macOS Sierra 
  * Tested on (emulator/device - details) : API 22, CPU x86 5GB (Pixel 2)
  
#### Description

Updated the icon of the app from the basic android icon to a bulb icon.
![screen shot 2018-04-14 at 12 44 59 pm](https://user-images.githubusercontent.com/19463512/38765864-20244c4a-3fe7-11e8-8843-441168ba0820.png)
![if_06_idea_2064481](https://user-images.githubusercontent.com/19463512/38765878-4298b7ca-3fe7-11e8-90ce-ed12adc0b1ca.png)

**Comment by drulabs** [comment]
@shubhamv1436 Created a separate issue for this. Check out this issue
https://github.com/UdacityAndroidDevScholarship/quiz-app/issues/17

Closing this issue
