### ISSUE TITLE
UI looking bad when opening nav drawer 

### ISSUE THREAD

**Issue by tavishjain** [UdacityAndroidDevScholarship/quiz-app#115]
**Please remove whichever section is not relevant.** (e.g. If you are creating a feature request issue, remove all bug and UI enhancement related details below)

**Is it a? (pick one)**

- [ ] UI Enhancement Request

### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * Android studio version : 3.0.1
  * Operating system : Windows
  * Tested on (emulator/device - details) : Xiaomi Redmi Note 4
  
### The Bug:
  * Description: Status bar color not looking nice when nav drawer opened
  * When does this occur?: on opeing nav drawer
  * attach screenshot / stacktrace: 
![whatsapp image 2018-05-08 at 1 13 40 am](https://user-images.githubusercontent.com/31106411/39721692-ed0e2086-525d-11e8-905b-a8024f5ac5bd.jpeg)

#### As per your understanding what is:
  * Expected behaviour: ______
  * Actual Behaviour: ______

#### Steps to reproduce:
  1. _____
  2. _____
  3. _____
  ...

### Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
  * If you have an idea about the technical background of the ticket, please share it.

#### Feature Description

Please describe the feature you want to add to the project.

#### Description

Please describe the UI changes/enhancements you want to add to the project. Try Uploading a screenshot/image for reference.

**Comment by xsahil03x** [comment]
@tavishjain also share a solution which you would like to see 😄

**Comment by tavishjain** [comment]
@xsahil03x just making the status bar transparent would do it. I didnt do this as making a pr with just one line changed would seem very odd

**Comment by CoderVishalSehgal** [comment]
@tavishjain Don't worry I'll do it.

**Comment by aditisoni8899** [comment]
@tavishjain Thank you for raising this issue. Our team had already taken care of this. Now the code is the repository is updated please have a look. Closing this issue as it is done now.
