### ISSUE TITLE
No sign of data loading or not

### ISSUE THREAD

**Issue by tavishjain** [UdacityAndroidDevScholarship/quiz-app#123]
**Please remove whichever section is not relevant.** (e.g. If you are creating a feature request issue, remove all bug and UI enhancement related details below)

**Is it a? (pick one)**

- [ ] Feature Request

### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * Android studio version : 3.0.1
  * Operating system : Windows
  * Tested on (emulator/device - details) : Redmi Note 4
  
### The Bug:
  * Description: On devices with a slow internet connection, there is no sign of checking whether the data is loading or not
  * When does this occur?: _____
  * attach screenshot / stacktrace: ss attached

![whatsapp image 2018-05-08 at 9 34 31 pm](https://user-images.githubusercontent.com/31106411/39768727-ca9fcce8-5307-11e8-92df-d09bf2b8b4c9.jpeg)

#### As per your understanding what is:
  * Expected behaviour: It should show a progress bar or something to show the status
  * Actual Behaviour: ______

#### Steps to reproduce:
  1. _____
  2. _____
  3. _____
  ...

### Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
  * If you have an idea about the technical background of the ticket, please share it.

#### Feature Description

Please describe the feature you want to add to the project.

#### Description

Please describe the UI changes/enhancements you want to add to the project. Try Uploading a screenshot/image for reference.

**Comment by tavishjain** [comment]
I am working on this

**Comment by drulabs** [comment]
@tavishjain this is yet to be planned and implemented. Will create tickets for cosmetic changes soon. Closing the issue now.

**Comment by kesari-vamshi** [comment]
I had same problem
