### ISSUE TITLE
Overlap of Creator name & Deadline in Quiz list for long text

### ISSUE THREAD

**Issue by arushi26** [UdacityAndroidDevScholarship/quiz-app#124]
**Is it a? (pick one)**
- [x] Bug Report

### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * Android studio version : 3.0.1
  * Operating system : Windows 10
  * Tested on (emulator/device - details) : Samsung On Max
  
### The Bug:
  * Description: Text overlaps in quiz list item in cases
  * When does this occur?:  When Creator name and Deadline detail text length is long. 
  * attach screenshot / stacktrace: 
![image](https://user-images.githubusercontent.com/2716159/39761390-990f143e-52f5-11e8-8080-bbde333adcbd.png)

#### As per your understanding what is:
  * Expected behaviour: Text should not overlap
  * Actual Behaviour: Overlapping present

#### Steps to reproduce:
  1. Go to main screen with quiz list.
  2. View item with Deadline = None

**Comment by jainakshansh** [comment]
@arushi26 Has this issue been solved already?

**Comment by arushi26** [comment]
@jainakshansh I raised a PR with code changes #125

**Comment by drulabs** [comment]
This issue is resolved, Please reopen this issue if you notice it again.
