### ISSUE TITLE
Home Screen Filter Handler

### ISSUE THREAD

**Issue by aditisoni8899** [UdacityAndroidDevScholarship/quiz-app#144]
**Complete By 12th May 2018 08:00 PM**

When HomeScreen filter is selected show appropriate message if there are no items to display.

1. `No bookmarked Quiz`.- Bookmark filter 
2. `All Quizzes Attempted` - Unattempted filter
3. `No Attempts yet` - Attempted filter

**Note** - Please figure out where to make changes without breaking the current design.

**Reference design**-
* Bookmarks Filter-
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#bookmark-filter-when-no-quizzes-bookmarked

* Unattempted Filter-
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#unattempted-filter-when-no-quizzes-are-left

* Attempted Filter-
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#attempted-filter-when-no-quizzes-are-attempted

**Assets**
https://drive.google.com/open?id=1nmuNqU5PpBlN_Yj9wwbFPx5z_Fo7jpuR

**Comment by PratyushaThumiki** [comment]
Shall I work on this?

**Comment by CoderVishalSehgal** [comment]
@PratyushaThumiki yes go ahead 👍

**Comment by intkhabahmed** [comment]
@CoderVishalSehgal I am working on it

**Comment by aditisoni8899** [comment]
@intkhabahmed Sure go ahead.

**Comment by CoderVishalSehgal** [comment]
@intkhabahmed yes sure go ahead!! 👍

**Comment by intkhabahmed** [comment]
@CoderVishalSehgal do you have the icons used in mockup or should I download again

**Comment by CoderVishalSehgal** [comment]
@intkhabahmed I've attached the assets link in the issue and you can also use your icons and make better.

**Comment by drulabs** [comment]
Merged @intkhabahmed's PR for this. Closing the issue.
