### ISSUE TITLE
Can you export data in Json format?

### ISSUE THREAD

**Issue by hilalsaim** [UdacityAndroidDevScholarship/quiz-app#169]
**Please remove whichever section is not relevant.** (e.g. If you are creating a feature request issue, remove all bug and UI enhancement related details below)

**Is it a? (pick one)**

- [ ] Bug

- [x] Feature Request

- [ ] UI Enhancement Request

### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * Android studio version : _____
  * Operating system : _____
  * Tested on (emulator/device - details) : _____
  
### The Bug:
  * Description: _____
  * When does this occur?: _____
  * attach screenshot / stacktrace: _____

#### As per your understanding what is:
  * Expected behaviour: ______
  * Actual Behaviour: ______

#### Steps to reproduce:
  1. _____
  2. _____
  3. _____
  ...

### Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
  * If you have an idea about the technical background of the ticket, please share it.

#### Feature Description

Please describe the feature you want to add to the project.

#### Description

Please describe the UI changes/enhancements you want to add to the project. Try Uploading a screenshot/image for reference.

**Comment by drulabs** [comment]
This issue is empty, no data or details, closing the issue.

**Comment by hilalsaim** [comment]
Can you export the data in json format to export to Firebase?

**Comment by hilalsaim** [comment]
I want to connect with my own firebase
