### ISSUE TITLE
Logo creation

### ISSUE THREAD

**Issue by drulabs** [UdacityAndroidDevScholarship/quiz-app#17]
Create a suitable logo for quiz app. Here are the requirements:
- Should be simplistic and unique
- Should define the purpose
- Should be in all sizes (mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi)
- Name it ic_launcher.png
- It will be good if it is adaptive
- Monochrome icons for notifications

Add icons to mipmap folder and create a PR to the **development** branch.

**Comment by nihanth876** [comment]
Guys I created a quiz logo and am uploading it here tell me if I can work on this
![launcher](https://user-images.githubusercontent.com/34400175/38987210-99464da4-43ec-11e8-9d8b-3a80fbed4d34.PNG)

**Comment by sagarsrao** [comment]
Hey Nihanth.We appreciate your work.But this is not the one which we are looking.Kindly follow a material design for the app logo.
1.Your app logo is not having proper color assets.
2.It's not very much creative.Kindly think out of the box.come up with good quiz logo's

**Comment by pushpalroy** [comment]
I would like to work on this.

**Comment by thayumaanavan** [comment]
@pushpalroy yes, Go ahead

**Comment by anshumandubey** [comment]
![quizapplogo](https://user-images.githubusercontent.com/10119668/39202663-2dabf0b2-4810-11e8-9d9f-735d24d20d4f.png)

How is this??

**Comment by anshumandubey** [comment]
![quizapplogo](https://user-images.githubusercontent.com/10119668/39202732-6c1ba82e-4810-11e8-81e7-4e8ad89110ba.png)
How is this??

**Comment by vansh1sh** [comment]
@anshumandubey Nice job! It looks good, but please create a PR for us to review. Make sure to follow the given issue description.

 Just a suggestion: Try changing the color to a darker one so that it matches the app mockups theme.

**Comment by vansh1sh** [comment]
@swatisingh0960
Nice job, I appreciate your efforts but I think that the logo could be improved a lot. Use a better color combination. Also, try making a logo which defines the purpose of the app.

After making the changes, you can create a PR following the guidelines.

**Comment by ashishkumar160** [comment]
![final](https://user-images.githubusercontent.com/16983116/39475453-e3d09072-4d75-11e8-917e-cfde042d776f.png)

Hey how about this logo for the app?

**Comment by vansh1sh** [comment]
@ashishkumar160 Hey, it looks good, but I would suggest you to try some darker colors. I guess it's trying to potray a Q shape, right? Maybe few more changes can make it look even more better.

**Comment by ashishkumar160** [comment]
@vansh1sh The UI's primary color is dark grey so I thought light colors will be more visible. Do you want me to change to darker colors?

**Comment by vansh1sh** [comment]
@ashishkumar160 You can try. From my perspective I think it'll look better with darker colors.

**Comment by animeshroydev** [comment]
@drulabs @vansh1sh Here are few icons of **quiz app** that I designed. Do give your feedback on it...
[quiz-App-Icon.pdf](https://github.com/UdacityAndroidDevScholarship/quiz-app/files/1966983/quiz-App-Icon.pdf)

**Comment by animeshroydev** [comment]
@vansh1sh Can you please give me the colour code of the app theme. So that the ICON matches with App.

**Comment by vansh1sh** [comment]
You can find them here :
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups

It's not mandatory to use these colors only, but the color shouldn't be too abstract from the ones used in the app.

**Comment by ashishkumar160** [comment]
![color](https://user-images.githubusercontent.com/16983116/39521327-b1f6010c-4e2b-11e8-8de7-73ae6b5d5a34.png)

Hey is this color fine?

![dahejf](https://user-images.githubusercontent.com/16983116/39521328-b32c91bc-4e2b-11e8-8bda-5401df68c002.jpg)

I created one more kinda same logo.

**Comment by animeshroydev** [comment]
@vansh1sh Should I make the pull request with the first icon?

**Comment by vibhuti16** [comment]
![ic_launcher](https://user-images.githubusercontent.com/4936653/39618791-f5f0980e-4fa2-11e8-81d7-852dca0ff892.png)

**Comment by vibhuti16** [comment]
![web_hi_res_512](https://user-images.githubusercontent.com/4936653/39623069-123115ca-4fb2-11e8-8d59-5becc7ec1148.png)

**Comment by vibhuti16** [comment]
![web_hi_res_512](https://user-images.githubusercontent.com/4936653/39626842-42a93764-4fc1-11e8-8004-b424ac013636.png)
![web_hi_res_512](https://user-images.githubusercontent.com/4936653/39626847-49f74ad8-4fc1-11e8-9601-75c046cd983b.png)

**Comment by vibhuti16** [comment]
![web_hi_res_512](https://user-images.githubusercontent.com/4936653/39626892-71284364-4fc1-11e8-9aab-c633e67ba591.png)

**Comment by vibhuti16** [comment]
![untitled](https://user-images.githubusercontent.com/4936653/39626904-7f61eeda-4fc1-11e8-8725-1fc0b8c02510.png)

**Comment by vibhuti16** [comment]
![untitled](https://user-images.githubusercontent.com/4936653/39627054-06c6a6d6-4fc2-11e8-8109-da6901f2cc86.png)

**Comment by nihanth876** [comment]
I tried an idea tell me if you like it i will create a pull request or if you like the idea you guys too can recreate it.
The green,red,yellow give the 3 types of difficulty we are using in our app.
Since our quizzes are mainly on android so the middle icon is the android icon
And the "Q" shape indicates questions.
![quizapplogo](https://user-images.githubusercontent.com/34400175/39630773-ff7622ec-4fcd-11e8-9523-ae0f4769bef3.PNG)

**Comment by vansh1sh** [comment]
@ashishkumar160 The dark blue shade looks good to me. You can update your PR if you want, further we'll decide the logo depending on team votes.

**Comment by vansh1sh** [comment]
@animeshroydev @vibhuti16 @nihanth876 Guys, go ahead and create a PR.

Nihanth for some reason the logo looks pixelated, please make sure to fix that.

**Comment by vibhuti16** [comment]
![ic_launcher](https://user-images.githubusercontent.com/4936653/39633359-5e06bed2-4fd5-11e8-8ff2-bc6ad4729269.png)

**Comment by nihanth876** [comment]
Yeah thanks for pointing that out @vanish1sh will make sure the changes are made

**Comment by nishank95** [comment]
Quiz app logo welcome for suggestions
![quiz app logo](https://user-images.githubusercontent.com/25129671/39660670-b80f4e6c-5061-11e8-81b3-abec8712fcb5.png)

**Comment by PratyushaThumiki** [comment]
![quizlogo](https://user-images.githubusercontent.com/36478864/39770251-17c6cc48-530c-11e8-82b7-4f17938a6388.png)
Please give your suggestions. If it's good, I'll submit a PR

**Comment by vibhuti16** [comment]
@PratyushaThumiki ill vote for you

**Comment by simran312** [comment]
![image](https://user-images.githubusercontent.com/39170378/39889945-f06c6f3e-54b6-11e8-95af-8a8e65cce334.png)

**Comment by pushpalroy** [comment]
![youwritersqdogsear](https://user-images.githubusercontent.com/19844292/39891439-3226ea86-54bb-11e8-8c4c-d3127a1975a9.png)

Logo in 512 x 512 px. Material design style. If its accepted, I'm ready to send a PR. Thanks.

**Comment by CoderVishalSehgal** [comment]
Closing this issue. Most appropriate Logo will be select soon.
