### ISSUE TITLE
Login screen UI

### ISSUE THREAD

**Issue by drulabs** [UdacityAndroidDevScholarship/quiz-app#18]
Complete by: 16-April-2018, EOD

- Only Google Login (Only UI)
- No mockup. Only implementation (XML Layout)

**Note**: App's color scheme will be decided based on the best UI implementation.

Sample UI Mockup : https://drive.google.com/open?id=1kCM_axXbQkgSOD7iAhxI0gCaxMQ_OdVl

**Comment by AjaySharvesh3** [comment]
Shall I claim this @drulabs

**Comment by AjaySharvesh3** [comment]
Sure @thayumaanavan I'm working on this issue.

**Comment by Jap-Leen** [comment]
Hi! I would like to work on this issue. Thanks!

**Comment by thayumaanavan** [comment]
Yes, you can start working @Jap-Leen

**Comment by intkhabahmed** [comment]
@thayumaanavan why are you assigning one issue to multiple people?

**Comment by Jap-Leen** [comment]
@intkhabahmed many people can work on the same issue and submit their PR before the deadline. The best PR will be finally merged into the project.

**Comment by intkhabahmed** [comment]
but as you can see the mockup is same and code to make it will be same obviously, so how the quality will be defined, because its a layout code and not logical code

**Comment by thayumaanavan** [comment]
@intkhabahmed Adding to @Jap-Leen 
We have more contributors(currently around 500 in collab channel) so if we assign one person per issue, others will not get a chance to contribute. We wanted to give chance for everyone.
Each will have different way of thinking and implementing the same functionality. We kept deadlines so that we can have a demo app before end of phase 1. 

Bonus point  is it will help in getting selected for phase 2 as well. 😉

**Comment by thayumaanavan** [comment]
@intkhabahmed mock-up given in the link is for sample purpose. You can come up with different design.

**Comment by intkhabahmed** [comment]
So I can also work on it then?

**Comment by thayumaanavan** [comment]
Yes you can @intkhabahmed

**Comment by JuhiGupta77** [comment]
Hello, could I work on Login app

**Comment by thayumaanavan** [comment]
Yes you can @JuhiGupta77

**Comment by JuhiGupta77** [comment]
How to submit the project?

**Comment by thayumaanavan** [comment]
@JuhiGupta77 once you are done with the layout, you can create PR to our Dev branch.
We will select the best one after deadline. For more info, you can check out the [contribution guidelines](https://github.com/UdacityAndroidDevScholarship/quiz-app/blob/master/CONTRIBUTING.md) and you can also post your queries in quiz slack channel.

**Comment by sidhuparas** [comment]
Let me give it a try. One question: who will decide the best one? Will there be voting or will mods/co-mods select the one?

**Comment by nihanth876** [comment]
can i work on this issue

**Comment by CoderVishalSehgal** [comment]
@nihanth876 Yes go ahead.

**Comment by sagarsrao** [comment]
yes

**Comment by kaushiknsanji** [comment]
Can I also try on this?

**Comment by thayumaanavan** [comment]
yes @kaushiknsanji

**Comment by Devesh1396** [comment]
I will work on this!

**Comment by derrickabreo** [comment]
I'll try to do one as well.

**Comment by CoderVishalSehgal** [comment]
@derrickabreo sure, but take care of the contribution and coding guidelines. :)

**Comment by ritesh-singh** [comment]
How the mods and co-mods are gonna decide the best layout.
Is it on the basis of

1. How it is designed in terms of UI, or
2. How the performance of the layout is, by using **Hierarchy Viewer** or
3. The layout is designed in a way, such that it supports different screens, or
4. If hardcode strings and all are used or not, 
or you guys will be considering all above.

And, if considering all above checks, then for every PR you have to run and check everyones apk.

I feel, allowing everyone to do the same task is not a right approach, maybe you can allow 2 to 3 people and ask him to consider all of the above as per mock. And then on the basis of his/her work, you can consider next time.

Just my thought.

Happy coding..!!

**Comment by aditisoni8899** [comment]
@ritesh-singh Thank you for the suggestion. I totally agree with your thought. But we have a workaround for solving this problem. Our team has prepared a PR template in which the contributor needs to submit a screenshot of his/her work before and after solving the issue. This thing will reduce our overhead and help us to manage the PR's. As in above comments @thayumaanavan has mentioned we are more than 500 people and by assigning a task to only 2 to 3 is not an efficient way. We want that every scholar will be able to contribute to our project.

**Comment by ritesh-singh** [comment]
@aditisoni8899 Great. Now, I am thinking of doing the same in blood donation app. 😆

**Comment by vansh1sh** [comment]
@ritesh-singh Additionally, If there is some hardcoded strings/in-efficient code used, we will ask the contributor to make the required changes/corrections and commit the improved code. Github provides a very good functionality for the same.

**Comment by aditisoni8899** [comment]
@ritesh-singh Great! It is all about learning from each other :) Go ahead. And do Let us know if you have something great which we can implement in our project.

**Comment by nishank95** [comment]
Can anybody tell me whats the deadline to submit the Login screen UI

**Comment by vansh1sh** [comment]
We'll be closing this issue since the deadline has passed. PRs will be reviewed shortly.
