### ISSUE TITLE
Get Details Page UI

### ISSUE THREAD

**Issue by vansh1sh** [UdacityAndroidDevScholarship/quiz-app#19]
Complete by: 19 April 2018 EOD.

- It is a one time screen after a user authenticates. 

The fields should include:
- Name
- Photo (Use an image from your google account OR select an avatar from a list)
- Slack Handle
- Select your track spinner.
- Email (Not editable, only Text view)
- Submit/Next Button

A sample UI :
 
<img src="https://drive.google.com/uc?export=download&id=1Yvr4IGiS_EzYe_uexOZkah7DuVVVYbbq" width="360" height="640">

**Comment by thayumaanavan** [comment]
Yes @derrickabreo please go ahead.

**Comment by abanidas** [comment]
Can I work on this UI ? What is the deadline?

**Comment by thayumaanavan** [comment]
Yes @abanidas. Currently it doesn’t have deadline. Anyways, I will check with @vansh1sh and update you asap.

**Comment by YuganshT79** [comment]
Will try to implement something ✌️

**Comment by vansh1sh** [comment]
@abanidas It needs to be completed by 17-April 2018 EOD.

**Comment by drulabs** [comment]
Also, ensure you follow our [contribution](https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/Contribution-Guidelines) and [coding style](https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/Code-Style-Guidelines) guidelines.

**Comment by derrickabreo** [comment]
Should we create a new Activity for this or use an existing one?

**Comment by CoderVishalSehgal** [comment]
@derrickabreo you just have to create a **layout** file(_Xml_).

**Comment by abanidas** [comment]
@drulabs sure,  I will follow the guidelines.

**Comment by abanidas** [comment]
@CoderVishalSehgal I have created a new Activity. So we will have to make pull request with only the layout file?

**Comment by CoderVishalSehgal** [comment]
@abanidas don't worry, for now just PR only layout file :)

**Comment by sidhuparas** [comment]
I think I can give it a try. By the way, since the deadline is today, I think a "High Priority" label should be added to it.

**Comment by derrickabreo** [comment]
What is select your track?

**Comment by nishank95** [comment]
I have finished designing layout page what should i add for PR whole project or just the detail_layout.xml file

**Comment by thayumaanavan** [comment]
@nishank95  when you create PR from your forked repo, it will showing only changed file.

**Comment by sud8443** [comment]
@thayumaanavan can still I work on this?

**Comment by thayumaanavan** [comment]
@sud8443 yes.. go ahead. We have extended the deadline.

**Comment by YuganshT79** [comment]
What is the Deadline for this issue?

**Comment by vansh1sh** [comment]
Deadline extended: 19 April 2018 EOD.

**Comment by AjaySharvesh3** [comment]
Shall I work on this issues? @vansh1sh

**Comment by AjaySharvesh3** [comment]
ONly the UI Changes or Business Logic too ??

**Comment by aditisoni8899** [comment]
@AjaySharvesh3 Yes go ahead :+1: only UI is required.

**Comment by animeshroydev** [comment]
@vansh1sh and other mods Will you guys please expand the EOD just for 1 days(20th April).

**Comment by animeshroydev** [comment]
I requested to extend the deadline by 20th April but mistakenly I deleted that comment earlier.  I somehow completed it. So please accept the pull request.

**Comment by aditisoni8899** [comment]
@animeshroydev sure.

**Comment by vansh1sh** [comment]
Closing this issue as it has been completed.
