### ISSUE TITLE
Wrong spellings in Issue Template.

### ISSUE THREAD

**Issue by DhruvamSharma** [UdacityAndroidDevScholarship/quiz-app#32]
**Please remove whichever section is not relevant.** (e.g. If you are creating a feature request issue, remove all bug and UI enhancement related details below)

**Is it a? (pick one)**

- [] Bug

- [x] Feature Request

- [ ] UI Enhancement Request

## Feature Request

The spellings are wrong.

#### Feature Description

The spelling of enhancement is wrong.

**Comment by AjaySharvesh3** [comment]
@DhruvamSharma Shall I work on this issue?

**Comment by vansh1sh** [comment]
Resolved.
