### ISSUE TITLE
Navigation Drawer UI

### ISSUE THREAD

**Issue by aditisoni8899** [UdacityAndroidDevScholarship/quiz-app#44]
Complete By: 24 April 2018 EOD

This is the Navigation Drawer UI for complete app navigation.

Requirements:

* It should have a cover image with profile picture, name and slack handle.
* Pencil icon at the top right of the cover image to open edit profile screen in the upcoming issue.
* QuizList line item: New quiz arrival indicator should be on this item. Also, this item should show total no. of quizzes.
* Notification line item: This should have an indicator to show total no. of new notifications.
* Resource line item: New resource arrival indicator should be on this item.
* **Every line item should have an appropriate icon beside it.**
* Other items in the drawer same as mentioned in the mockup.

Sample UI link: https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#navigation-drawer

**Note**: Creative ideas are most welcome but make sure you are not deviating too much from the theme of the app. Also, the current mockup for this screen will soon be updated to reflect the above requirements.

**Comment by pjoshi08** [comment]
@intkhabahmed Please go ahead.

**Comment by ibhavikmakwana** [comment]
I would like to work on this.

**Comment by aditisoni8899** [comment]
@ibhavikmakwana Sure!
 Looking forward to it.

**Comment by AjaySharvesh3** [comment]
Shall I work on this???? @aditisoni8899

**Comment by PratyushaThumiki** [comment]
I would like to work on this issue! Can I?

**Comment by thayumaanavan** [comment]
@AjaySharvesh3 @PratyushaThumiki  please go ahead.

**Comment by drulabs** [comment]
@AjaySharvesh3 @PratyushaThumiki please go ahead.

**Comment by shubhamv1436** [comment]
I would like to work on it.

**Comment by thayumaanavan** [comment]
@shubhamv1436 yes, go ahead

**Comment by visnu-bochiwal** [comment]
I'm going to work upon this.

**Comment by AjaySharvesh3** [comment]
@visnu-bochiwal Already PR is accepted for this. Mods are reviewing the PR so please claim some other issue.

**Comment by visnu-bochiwal** [comment]
ok than How do I know which issue is currently open?

**Comment by thayumaanavan** [comment]
@visnu-bochiwal we are yet to open new issues. I think only logo creation is open.
You can find the open issue by seeing the deadline mentioned in the issue description.

**Comment by thayumaanavan** [comment]
Issue resolved. Merged @AjaySharvesh3 's PR #98  for this.
