### ISSUE TITLE
Create Notification Table

### ISSUE THREAD

**Issue by drulabs** [UdacityAndroidDevScholarship/quiz-app#47]
**Finish by 25-April-2018 EOD**

Create a table for notifications. Use `data/local/DBHelper.java`. It needs to be exactly in line with what we learned in our course
- A contract for notification table. Please ensure you follow instructions from SQLite lesson. 
- A create table statement, make sure you use the contract, create a separate `private static final string` variable in the class and store the SQL create table statement for notification table
- DO NOT create a Content Provider. Since we are not planning to share any data with other apps.
- Also, create a POJO object (Notification) for this and put it under `data/models`. Use annotations similar to other models

here is the notification object:

```javascript
{
	"timestamp": 1524224984,
	"title": "SQLite - not null",
	"description": "description - not null",
	"from": "Kaushal - not null",
	"type": "quiz/discussion/direct/announcement - not null",
	"action": "id of quiz - nullable",
	"extra1": "extra info - nullable",
	"extra2": "extra info - nullable"
}
```

**Note**:
- Please check-in relevant files only

**Comment by GauravR31** [comment]
Can I take this up?

**Comment by nishank95** [comment]
I would like to work on this?

**Comment by drulabs** [comment]
@nishank95 sure. Please ensure you follow the SQLite lesson instructions.

**Comment by derrickabreo** [comment]
I would like to try to implement as well.

**Comment by vivekpanchal** [comment]
would like to work in this too

**Comment by vansh1sh** [comment]
Sure @vivekpanchal

**Comment by derrickabreo** [comment]
I did not understand point 2.

**Comment by visnu-bochiwal** [comment]
I want to do this. So Can I?

**Comment by drulabs** [comment]
@huzefaraja `I'm in` is sufficient. Sure, you are in.

**Comment by drulabs** [comment]
@visnu-bochiwal please go ahead.

**Comment by thayumaanavan** [comment]
@SrikarNanduri yes, please go ahead.

**Comment by akshaychopra96** [comment]
I am also interested in this. And this will be my first contribution. So excited. 
I hope I can also do this?

**Comment by akshaychopra96** [comment]
I have made the changes. But due to the lack of my knowledge on how to use GitHub, I have spent 2 hours still not be able to create a pull request. Please help me what to do.    :(

**Comment by drulabs** [comment]
Closing the issue. Merged [PR 50](https://github.com/UdacityAndroidDevScholarship/quiz-app/pull/50) for this.
