### ISSUE TITLE
My Profile UI

### ISSUE THREAD

**Issue by vansh1sh** [UdacityAndroidDevScholarship/quiz-app#66]
**Complete By: 30th April 2018, EOD.**

This is the profile page where users can edit their profile details anytime.

Changes required in : **activity_user_profile.xml**

Requirements:

- Name (Editable)
- Slack Handle (Editable)
- Photo/Avatar (Changeable)
    A) Users can either select an avatar from a list of 10-20 avatars
    B) OR Use the image fetched after the Gmail login.
    Note: Feature for manually uploading images (from device) is not required.
- Track (Not Editable) (Should have only “Android Developer Track” for now) 
- Email (Not editable)
- Submit/Next Button

Sample UI link: https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#see-user-profile-activity

**Comment by YuganshT79** [comment]
Will work on this issue

**Comment by pushpalroy** [comment]
Will work on this issue.

**Comment by ibhavikmakwana** [comment]
I would like to work on this.

**Comment by sagarsrao** [comment]
Please go head.Kindly follow all the guidelines.

**Comment by GauravR31** [comment]
Can I work on this?

**Comment by sidhuparas** [comment]
I have a doubt. Is this UI challenge the same as the **Details Page UI** with a couple of changes? #19. I had made a pull request about a week ago: https://github.com/UdacityAndroidDevScholarship/quiz-app/pull/31. Should I modify it to make some new changes as instructed above or make a new pull request?

**Comment by aditisoni8899** [comment]
@sidhuparas In this screen, profile picture and a cover image should be editable along with slack handle and name. For now, the track should be non-editable and its default value should be "Android Developers Track". UI for this screen should be accordingly as this is not a one time screen and editing profile feature will be provided by this screen only.

**Comment by sayaMahi** [comment]
Will work on this.

**Comment by xsahil03x** [comment]
Can i work on this ?

**Comment by vansh1sh** [comment]
@xsahil03x The deadline for this issue has already been passed. We have a lot of other issues to which you can contribute. Please check out the issue tab on our Github repo. :)

**Comment by vansh1sh** [comment]
@shubhamv1436 The deadline has already passed but since you might have already started with it please create a PR before EOD.

**Comment by vansh1sh** [comment]
@shubhamv1436 Just a reminder, I'll be closing this issue soon. Please create a PR if you want to contribute to this issue.

**Comment by shubhamv1436** [comment]
@vansh1sh I have almost done it but I am facing an error and I am working on it...if possible you can close it tomorrow just give me today's night...I will submit a PR till tomorrow morning

**Comment by vansh1sh** [comment]
@shubhamv1436 Okay, no issue will be closing it tomorrow morning then. Please update us with it. Do reach out to us if you're stuck up on something for long. All the best :)

**Comment by shubhamv1436** [comment]
Thanks @vansh1sh ...It means a lot to me

**Comment by vansh1sh** [comment]
Resolved
