### ISSUE TITLE
Using boolean instead of Boolean

### ISSUE THREAD

**Issue by knightcube** [UdacityAndroidDevScholarship/quiz-app#72]
**Please remove whichever section is not relevant.** (e.g. If you are creating a feature request issue, remove all bug and UI enhancement related details below)

**Is it a? (pick one)**

- [ ] Bug

- [ ] Feature Request

- [x] Code Beautification
 
The basic difference in boolean and Boolean is that

- Boolean can be yes, no or NULL . It is an object wrapper for boolean
- boolean can be only yes or no

There is seldom a reason to use a Boolean over a boolean except in cases when an object reference is required, such as in a List.

**Solution
Replace Boolean with boolean
I want to work on this issue

**Comment by drulabs** [comment]
@knightcube thanks. Let's discuss on the PR.

**Comment by knightcube** [comment]
Sure

**Comment by drulabs** [comment]
@knightcube I am renaming the issue. Please see the comments in the PR for details.

**Comment by vansh1sh** [comment]
Resolved.
