### ISSUE TITLE
Notification Screen UI

### ISSUE THREAD

**Issue by thayumaanavan** [UdacityAndroidDevScholarship/quiz-app#75]
**Complete By: 3rd May 2018, EOD**

This notification page will be opened from Navigation drawer where all the app notification will be shown.

**Features**:
- Notification types(as tabs): New Quiz, Deadlines, Resources
- For each tab:
    - use Recycler view to list the notification messages according to it’s type.
    - List item should have image,Notification title,description,date
    - Unread notifications should be on top of the list
    - Clear notification option - swipe to delete(single item) or long press to multi-select delete(multiple item).
- Notification Details page should have description and button to redirect to the required page based on the notification type.
    - Button Name : *Open Quiz* (new quiz and deadlines type) or *Open Resource* (resources type)

Sample UIs: https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#notifications-activity
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#notification-detail-activity

**Comment by vibhuti16** [comment]
I will work on this

**Comment by nishank95** [comment]
Can i work on this issue

**Comment by jainakshansh** [comment]
Hello @thayumaanavan, is this issue still active?

**Comment by thayumaanavan** [comment]
@jainakshansh this is in review phase. We will be opening new issues by today. You can work on that.

**Comment by thayumaanavan** [comment]
Issue resolved. Merged @nishank95's PR for this.
