### ISSUE TITLE
Google login

### ISSUE THREAD

**Issue by drulabs** [UdacityAndroidDevScholarship/quiz-app#77]
Implement google login with firebase on the Sign In screen.

**Comment by AjaySharvesh3** [comment]
Shall I work on this?

**Comment by drulabs** [comment]
@AjaySharvesh3 No. This is already implemented. Will be merged in `development` branch soon.

**Comment by animeshroydev** [comment]
Hi, @drulabs Google login is not working on the development branch...

**Comment by AjaySharvesh3** [comment]
@animeshroydev said It's not working that's why I tried to make implement on this.

**Comment by animeshroydev** [comment]
@AjaySharvesh3 I would love to implement this but @drulabs said already implemented. Really confused...

**Comment by AjaySharvesh3** [comment]
@animeshroydev Cool.

**Comment by drulabs** [comment]
@animeshroydev as mentioned in previous comment `This is already implemented. Will be merged in development branch soon`. The implementation is in a separate branch. Right now we are merging this into `development` branch. After the merge you can take a pull from `development`.

Also, @animeshroydev and @AjaySharvesh3 please look for issues with `official` label, not `internal`. This issue is tagged `internal`.

**Comment by animeshroydev** [comment]
@drulabs Thanks for clarifying...

**Comment by drulabs** [comment]
@animeshroydev @AjaySharvesh3 it is merged now. Please check the `development` branch now. Closing the issue.
