### ISSUE TITLE
UI/UX Enhancement: Add filtering drop-down on Home screen.

### ISSUE THREAD

**Issue by CoderVishalSehgal** [UdacityAndroidDevScholarship/quiz-app#79]
**Complete By : 30th April 2018, EOD.**

*Requirements:*
- Remove the current toggle button(unattempted)
- Add these *Filtering* options :
   A) All
   B) Attempted
   C) Un-attempted
   D) Bookmarks.
- The menu *slides down* from the toolbar and after selecting an option it *slides up* again.

**Sample UI**
https://github.com/UdacityAndroidDevScholarship/quiz-app/wiki/App-Mockups#home-screen-list-filterdrop-down

**Note:** We have added a color palette on our wiki page for reference to maintain consistency throughout the app screens. Please use it for future contributions.

**Comment by visnu-bochiwal** [comment]
I want to work on this but I'm not able to figure it out that should I need to code Home fragment myself and then pass the parameter from ActivityMain.java to this fragment based on the chosen filter or make four separate fragments?

**Comment by CoderVishalSehgal** [comment]
@visnu-bochiwal you just have to prepare the UI for this and don't need to handle other things.

**Comment by abanidas** [comment]
@CoderVishalSehgal  @aditisoni8899 I want to work on this. 
Can I customize the design a little bit? Or it should be similar to the Sample UI?

**Comment by vansh1sh** [comment]
Resolved.
