### ISSUE TITLE
Notification for Quiz-App

### ISSUE THREAD

**Issue by sagarsrao** [UdacityAndroidDevScholarship/quiz-app#82]
**Finish By Tuesday, 02-May-2018, EOD**

Quiz App will support different types of notifications. For example `A new quiz is available notification`, `A new resource has been added notification`, `SQLite quiz deadline is approaching notification` etc. We will be using `Firebase Cloud Messaging (FCM)` to support this.

**You DON'T need to know FCM to work on this issue.**

1. **Raise a system notification**
- Create a notification helper class called NotificationUtils put it in `utils` package. (This class will not have any class level variables only public/private static methods like all utility classes)
- Create a method (`public static`) to create notification channel if it doesn't exist.
- Take all the necessary parameters to create a notification channel in above method, including `Context` and `channelName`.
- Create a `public static` method for creating a system notification, name it `createNotification(...)`
- Take `context` and `models/Notification` as parameter in above method.
- Use the parameters to raise a system notification. Use `NotificationCompat`.
- Notification icon should be based on `Notification.getType()`. Supported types are `quiz/resource/discussion/announcement`.

2. **Receive Firebase Cloud Message and issue a system notification**
- create a private method is `services/FBMessagingService` that takes `RemoteMessage` as parameter. Extract the data from RemoteMessage as `remoteMsg.getData()`. Payload will be:
```javascript
{
    "title": "notification title",
    "description": "description",
    "from": "Kaushal",
    "type": "quiz/discussion/...",
    "action": "something",
    "extra1": "extra1",
    "extra2": "extra2"
}
```
- Create class level constants to get the data. `e.g. public static final KEY_TITLE = "title" etc.`
- Create a `models/Notification` object from above data.
- Use `utils/NotificationUtils` class from previous step to raise a system notification.
- **Must pass `action, extra1, extra2` as intent extras in notification pending intent.**

**Comment by intkhabahmed** [comment]
Hey, I will work on it

**Comment by gupta-vibhuti** [comment]
Hey, I'm interested in working on this.

**Comment by drulabs** [comment]
@intkhabahmed @gupta-vibhuti please wait for some time before starting. pushing some changes.

**Comment by intkhabahmed** [comment]
ok

**Comment by drulabs** [comment]
@intkhabahmed @gupta-vibhuti you are good to go. You can work on this now. Don't forget to take a pull from `development` branch. Merging is done.

**Comment by drulabs** [comment]
Issue resolved. Merged @intkhabahmed's [PR](https://github.com/UdacityAndroidDevScholarship/quiz-app/pull/92) for this.
