### ISSUE TITLE
Store Notifications

### ISSUE THREAD

**Issue by drulabs** [UdacityAndroidDevScholarship/quiz-app#83]
**Finish by Tuesday, 02-May-2018**

1. Create methods in DBHandler to add a notification, to retrieve all notifications and search by text. Search in title and description. Use the `db` object in `DBHandler`.
Method signatures: 
- `addNotification(Notification notification)`
- `List<Notification> getAllNotifications(int startFrom, int limit)`
- `List<Notification> searchNotifications(String query, int startFrom, int limit)`

Ignore the `startFrom` and `limit` parameter for now. Search should be performed in `title` and `description` field of notification table.

Add signatures all the above methods in DataHandler too. Implement these methods in `AppDataHandler` and use the instance of `DBHandler` in the class to save notifications.

2. Private method in `services/FBMessagingService`->`storeNotification(RemoteMessage)` It should extract data from `RemoteMessage.getData()`, create a `models/Notification` Object and save it using `DataHandlerProvider.provide().saveNotification(...)`

Remote Message Payload defined in #82

**Comment by rahul7838** [comment]
Created the pull request for the 1st point. Please have a look.

**Comment by drulabs** [comment]
The issue is resolved. Merged @rahul7838's [PR](https://github.com/UdacityAndroidDevScholarship/quiz-app/pull/93) for resolving this issue. Closing the issue.
